# Generated by Django 4.2 on 2023-05-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default/placeholder.png', null=True, upload_to='media/post_thumbs'),
        ),
    ]
