# Generated by Django 4.2 on 2023-05-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_profile_birthdate_profile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experiences',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='home_img',
            field=models.ImageField(blank=True, default='default/placeholder.png', null=True, upload_to='users/thumb'),
        ),
        migrations.AddField(
            model_name='profile',
            name='home_skills',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default/UserProfile.png', null=True, upload_to='users/thumb'),
        ),
    ]
