# Generated by Django 4.2 on 2023-05-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_profile_experiences_profile_home_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='thumbnail',
            new_name='profile_img',
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
