# Generated by Django 4.2 on 2023-05-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_rename_thumbnail_profile_profile_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('birthdate', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('profile_img', models.ImageField(blank=True, default='default/UserProfile.png', null=True, upload_to='users/thumb')),
                ('adress', models.CharField(max_length=200, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('insta', models.URLField(null=True)),
                ('git', models.URLField(null=True)),
                ('linkedin', models.URLField(null=True)),
                ('home_img', models.ImageField(blank=True, default='default/placeholder.png', null=True, upload_to='users/thumb')),
                ('home_skills', models.TextField(null=True)),
                ('subtitle', models.CharField(max_length=200, null=True)),
                ('summary', models.TextField(null=True)),
                ('skills', models.TextField(null=True)),
                ('experiences', models.TextField(null=True)),
                ('education', models.TextField(null=True)),
                ('languages', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
