# Generated by Django 4.2 on 2023-05-29 15:28

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_pageprofile_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
